name: Build and Push Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_CICD_SA }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GCP_AR_HOST }}

      - name: Build and push patient-service
        run: |
          docker build -t ${{ secrets.GCP_AR_HOST }}/${{ secrets.GCP_PROJECT }}/ms-docker/patient-service:${{ github.sha }} ./patient-service
          docker push ${{ secrets.GCP_AR_HOST }}/${{ secrets.GCP_PROJECT }}/ms-docker/patient-service:${{ github.sha }}

      - name: Build and push application-service
        run: |
          docker build -t ${{ secrets.GCP_AR_HOST }}/${{ secrets.GCP_PROJECT }}/ms-docker/application-service:${{ github.sha }} ./application-service
          docker push ${{ secrets.GCP_AR_HOST }}/${{ secrets.GCP_PROJECT }}/ms-docker/application-service:${{ github.sha }}

      - name: Build and push order-service
        run: |
          docker build -t ${{ secrets.GCP_AR_HOST }}/${{ secrets.GCP_PROJECT }}/ms-docker/order-service:${{ github.sha }} ./order-service
          docker push ${{ secrets.GCP_AR_HOST }}/${{ secrets.GCP_PROJECT }}/ms-docker/order-service:${{ github.sha }}
