name: Terraform

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.3

      - name: Terraform fmt
        run: terraform fmt -recursive

      - name: Terraform validate
        run: |
          cd Terrform/Env/dev
          terraform init -backend=false
          terraform validate

  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.3

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TF_SA }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform init
        run: |
          cd Terrform/Env/dev
          terraform init

      - name: Terraform plan
        run: |
          cd Terrform/Env/dev
          terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: Terrform/Env/dev/tfplan

  apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.3

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_TF_SA }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Terraform init
        run: |
          cd Terrform/Env/dev
          terraform init

      - name: Terraform apply
        run: |
          cd Terrform/Env/dev
          terraform apply -auto-approve
